//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Present.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Present.Resources.EmbedStrings", typeof(EmbedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Already excluded.
        /// </summary>
        internal static string AlreadyExcluded {
            get {
                return ResourceManager.GetString("AlreadyExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} is already excluded..
        /// </summary>
        internal static string BlockRole_AlreadyExcluded {
            get {
                return ResourceManager.GetString("BlockRole_AlreadyExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members with the role {0} are now excluded from winning giveaways..
        /// </summary>
        internal static string BlockRole_Success {
            get {
                return ResourceManager.GetString("BlockRole_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is already excluded..
        /// </summary>
        internal static string BlockUser_AlreadyExcluded {
            get {
                return ResourceManager.GetString("BlockUser_AlreadyExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is now excluded from winning giveaways..
        /// </summary>
        internal static string BlockUser_Success {
            get {
                return ResourceManager.GetString("BlockUser_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        internal static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends.
        /// </summary>
        internal static string Ends {
            get {
                return ResourceManager.GetString("Ends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrants.
        /// </summary>
        internal static string Entrants {
            get {
                return ResourceManager.GetString("Entrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Entrants.
        /// </summary>
        internal static string ExcludedEntrants {
            get {
                return ResourceManager.GetString("ExcludedEntrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Exclusion added.
        /// </summary>
        internal static string ExclusionAdded {
            get {
                return ResourceManager.GetString("ExclusionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Exclusion removed.
        /// </summary>
        internal static string ExclusionRemoved {
            get {
                return ResourceManager.GetString("ExclusionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The giveaway **{0}** was created in {1}..
        /// </summary>
        internal static string GiveawayCreated_Description {
            get {
                return ResourceManager.GetString("GiveawayCreated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 Giveaway created.
        /// </summary>
        internal static string GiveawayCreated_Title {
            get {
                return ResourceManager.GetString("GiveawayCreated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway created.
        /// </summary>
        internal static string GiveawayCreated_Title_NoEmoji {
            get {
                return ResourceManager.GetString("GiveawayCreated_Title_NoEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a timestamp in the future..
        /// </summary>
        internal static string GiveawayCreation_FutureTimestamp {
            get {
                return ResourceManager.GetString("GiveawayCreation_FutureTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter either a Unix timestamp (in seconds), or a relative timestamp (e.g. 2d6h)..
        /// </summary>
        internal static string GiveawayCreation_InvalidTimestamp {
            get {
                return ResourceManager.GetString("GiveawayCreation_InvalidTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a description for the giveaway..
        /// </summary>
        internal static string GiveawayCreation_NoDescription {
            get {
                return ResourceManager.GetString("GiveawayCreation_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a title for the giveaway..
        /// </summary>
        internal static string GiveawayCreation_NoTitle {
            get {
                return ResourceManager.GetString("GiveawayCreation_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Failed to create giveaway.
        /// </summary>
        internal static string GiveawayCreationFailed {
            get {
                return ResourceManager.GetString("GiveawayCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway edited.
        /// </summary>
        internal static string GiveawayEdited_Title {
            get {
                return ResourceManager.GetString("GiveawayEdited_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 Giveaway of **{giveaway.Title}** has ended! If you&apos;ve won, you will be DM&apos;d by staff shortly. Please ensure that you have DMs enabled! If we can&apos;t reach you, you will forfeit your win..
        /// </summary>
        internal static string GiveawayEnded {
            get {
                return ResourceManager.GetString("GiveawayEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The giveaway {giveaway.Id} (**{giveaway.Title}**) ended with {winners}..
        /// </summary>
        internal static string GiveawayEnded_Description {
            get {
                return ResourceManager.GetString("GiveawayEnded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The giveaway {giveaway.Id} (**{giveaway.Title}**) ended with {winners}, but expected {giveaway.WinnerCount}..
        /// </summary>
        internal static string GiveawayEnded_FewWinners_Description {
            get {
                return ResourceManager.GetString("GiveawayEnded_FewWinners_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway ended with fewer winners than specified.
        /// </summary>
        internal static string GiveawayEnded_FewWinners_Title {
            get {
                return ResourceManager.GetString("GiveawayEnded_FewWinners_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The giveaway {giveaway.Id} (**{giveaway.Title}**) ended with no winners selected..
        /// </summary>
        internal static string GiveawayEnded_NoWinners_Description {
            get {
                return ResourceManager.GetString("GiveawayEnded_NoWinners_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway ended with no winners.
        /// </summary>
        internal static string GiveawayEnded_NoWinners_Title {
            get {
                return ResourceManager.GetString("GiveawayEnded_NoWinners_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway ended.
        /// </summary>
        internal static string GiveawayEnded_Title {
            get {
                return ResourceManager.GetString("GiveawayEnded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway Entrants.
        /// </summary>
        internal static string GiveawayEntrants {
            get {
                return ResourceManager.GetString("GiveawayEntrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway Information.
        /// </summary>
        internal static string GiveawayInformation {
            get {
                return ResourceManager.GetString("GiveawayInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified giveaway is currently active, and so cannot yet be redrawn..
        /// </summary>
        internal static string GiveawayIsActive {
            get {
                return ResourceManager.GetString("GiveawayIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified giveaway is not active, and so cannot be ended..
        /// </summary>
        internal static string GiveawayIsNotActive {
            get {
                return ResourceManager.GetString("GiveawayIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ENDED] GIVEAWAY: .
        /// </summary>
        internal static string GiveawayTitle_Ended {
            get {
                return ResourceManager.GetString("GiveawayTitle_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 GIVEAWAY: .
        /// </summary>
        internal static string GiveawayTitle_Ongoing {
            get {
                return ResourceManager.GetString("GiveawayTitle_Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified giveaway were unchanged..
        /// </summary>
        internal static string GiveawayUnchanged {
            get {
                return ResourceManager.GetString("GiveawayUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Invalid giveaway ID.
        /// </summary>
        internal static string InvalidGiveawayId {
            get {
                return ResourceManager.GetString("InvalidGiveawayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value `{0}` is not a valid ID..
        /// </summary>
        internal static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following IDs were ignored because they correspond to invalid or excluded members: {0}.
        /// </summary>
        internal static string InvalidKeepIds {
            get {
                return ResourceManager.GetString("InvalidKeepIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Invalid role.
        /// </summary>
        internal static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified role was not found..
        /// </summary>
        internal static string InvalidRole_Description {
            get {
                return ResourceManager.GetString("InvalidRole_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Invalid user.
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user was not found..
        /// </summary>
        internal static string InvalidUser_Description {
            get {
                return ResourceManager.GetString("InvalidUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter by hitting the button below..
        /// </summary>
        internal static string JoinGiveawayFooter {
            get {
                return ResourceManager.GetString("JoinGiveawayFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more details, see {0}..
        /// </summary>
        internal static string LogChannel_MoreDetails {
            get {
                return ResourceManager.GetString("LogChannel_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ No action taken.
        /// </summary>
        internal static string NoActionTaken {
            get {
                return ResourceManager.GetString("NoActionTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No giveaway with the ID `{0}` was found for this guild..
        /// </summary>
        internal static string NoGiveawayFound {
            get {
                return ResourceManager.GetString("NoGiveawayFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Winners.
        /// </summary>
        internal static string NumberOfWinners {
            get {
                return ResourceManager.GetString("NumberOfWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Exclusion Added.
        /// </summary>
        internal static string RoleExclusionAdded {
            get {
                return ResourceManager.GetString("RoleExclusionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Member.
        /// </summary>
        internal static string StaffMember {
            get {
                return ResourceManager.GetString("StaffMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} was not already excluded..
        /// </summary>
        internal static string UnblockRole_AlreadyExcluded {
            get {
                return ResourceManager.GetString("UnblockRole_AlreadyExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members with the role {0} are no longer excluded from winning giveaways..
        /// </summary>
        internal static string UnblockRole_Success {
            get {
                return ResourceManager.GetString("UnblockRole_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} was not already excluded..
        /// </summary>
        internal static string UnblockUser_AlreadyExcluded {
            get {
                return ResourceManager.GetString("UnblockUser_AlreadyExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is no longer excluded from winning giveaways..
        /// </summary>
        internal static string UnblockUser_Success {
            get {
                return ResourceManager.GetString("UnblockUser_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winners.
        /// </summary>
        internal static string Winners {
            get {
                return ResourceManager.GetString("Winners", resourceCulture);
            }
        }
    }
}
